import { DocumentItem, ActivityItem, WorkflowSettings, AnalyticsData } from '@/types';

export const MOCK_STATS = {
  totalDocuments: 248,
  processed: 231,
  pendingReview: 17,
  approved: 185,
};

export const MOCK_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-001',
    invoiceNumber: 'INV-2024-001',
    vendor: 'Acme Solutions Pvt Ltd',
    vendorEmail: 'billing@acmesolutions.com',
    amount: 42500,
    currency: 'INR',
    status: 'Review',
    date: '2024-10-14',
    dueDate: '2024-11-14',
    subtotal: 36016.95,
    tax: 6483.05,
    total: 42500,
    aiConfidence: 96,
    validationStatus: 'Passed',
    duplicateDetected: false,
    workflowDecision: 'Requires Human Review',
    reviewReason: 'Invoice amount exceeds automatic approval threshold.',
    issue: 'High invoice amount',
    fileType: 'pdf',
    fileSize: '1.4 MB',
  },
  {
    id: 'doc-002',
    invoiceNumber: 'INV-2024-002',
    vendor: 'CloudScale Technologies',
    vendorEmail: 'accounts@cloudscale.io',
    amount: 18200,
    currency: 'INR',
    status: 'Approved',
    date: '2024-10-13',
    dueDate: '2024-11-13',
    subtotal: 15423.73,
    tax: 2776.27,
    total: 18200,
    aiConfidence: 99,
    validationStatus: 'Passed',
    duplicateDetected: false,
    workflowDecision: 'Auto Approved',
    fileType: 'pdf',
    fileSize: '850 KB',
  },
  {
    id: 'doc-003',
    invoiceNumber: 'INV-2024-003',
    vendor: 'Apex Logistics Ltd',
    vendorEmail: 'finance@apexlogistics.in',
    amount: 31000,
    currency: 'INR',
    status: 'Review',
    date: '2024-10-12',
    dueDate: '2024-11-12',
    subtotal: 26271.19,
    tax: 4728.81,
    total: 31000,
    aiConfidence: 74,
    validationStatus: 'Warning',
    duplicateDetected: false,
    workflowDecision: 'Requires Human Review',
    reviewReason: 'AI confidence score (74%) is below 80% threshold.',
    issue: 'Low AI confidence',
    fileType: 'png',
    fileSize: '2.1 MB',
  },
  {
    id: 'doc-004',
    invoiceNumber: 'INV-2024-004',
    vendor: 'OfficeSupplies Express',
    vendorEmail: 'support@officesupplies.com',
    amount: 8450,
    currency: 'INR',
    status: 'Approved',
    date: '2024-10-11',
    dueDate: '2024-11-11',
    subtotal: 7161.02,
    tax: 1288.98,
    total: 8450,
    aiConfidence: 98,
    validationStatus: 'Passed',
    duplicateDetected: false,
    workflowDecision: 'Auto Approved',
    fileType: 'pdf',
    fileSize: '620 KB',
  },
  {
    id: 'doc-005',
    invoiceNumber: 'INV-2024-005',
    vendor: 'DevOps Tooling LLC',
    vendorEmail: 'invoices@devopstooling.net',
    amount: 25000,
    currency: 'INR',
    status: 'Review',
    date: '2024-10-10',
    dueDate: '2024-11-10',
    subtotal: 21186.44,
    tax: 3813.56,
    total: 25000,
    aiConfidence: 95,
    validationStatus: 'Warning',
    duplicateDetected: true,
    workflowDecision: 'Requires Human Review',
    reviewReason: 'Possible duplicate detected (matching vendor & amount with INV-2024-002).',
    issue: 'Possible duplicate',
    fileType: 'pdf',
    fileSize: '1.1 MB',
  },
  {
    id: 'doc-006',
    invoiceNumber: 'INV-2024-006',
    vendor: 'Vanguard Cyber Security',
    vendorEmail: 'billing@vanguardsec.com',
    amount: 54000,
    currency: 'INR',
    status: 'Processing',
    date: '2024-10-09',
    dueDate: '2024-11-09',
    subtotal: 45762.71,
    tax: 8237.29,
    total: 54000,
    aiConfidence: 88,
    validationStatus: 'Passed',
    duplicateDetected: false,
    workflowDecision: 'Requires Human Review',
    fileType: 'pdf',
    fileSize: '3.4 MB',
  },
  {
    id: 'doc-007',
    invoiceNumber: 'INV-2024-007',
    vendor: 'Global Shipping Co',
    vendorEmail: 'accounts@globalshipping.in',
    amount: 14500,
    currency: 'INR',
    status: 'Rejected',
    date: '2024-10-08',
    dueDate: '2024-11-08',
    subtotal: 12288.14,
    tax: 2211.86,
    total: 14500,
    aiConfidence: 62,
    validationStatus: 'Failed',
    duplicateDetected: false,
    workflowDecision: 'Rejected',
    reviewReason: 'Missing GSTIN and mandatory tax breakdown details.',
    issue: 'Missing information',
    fileType: 'jpg',
    fileSize: '1.8 MB',
  },
  {
    id: 'doc-008',
    invoiceNumber: 'INV-2024-008',
    vendor: 'Starlight Media House',
    vendorEmail: 'media@starlight.co',
    amount: 19800,
    currency: 'INR',
    status: 'Approved',
    date: '2024-10-07',
    dueDate: '2024-11-07',
    subtotal: 16779.66,
    tax: 3020.34,
    total: 19800,
    aiConfidence: 97,
    validationStatus: 'Passed',
    duplicateDetected: false,
    workflowDecision: 'Auto Approved',
    fileType: 'pdf',
    fileSize: '920 KB',
  },
];

export const MOCK_ACTIVITIES: ActivityItem[] = [
  {
    id: 'act-001',
    documentId: 'doc-001',
    invoiceNumber: 'INV-2024-001',
    action: 'Invoice uploaded by Harsh',
    user: 'Harsh Mehta',
    timestamp: '10 minutes ago',
    type: 'upload',
  },
  {
    id: 'act-002',
    documentId: 'doc-001',
    invoiceNumber: 'INV-2024-001',
    action: 'AI extracted vendor & 8 line items with 96% confidence',
    user: 'DocFlow AI',
    timestamp: '9 minutes ago',
    type: 'process',
  },
  {
    id: 'act-003',
    documentId: 'doc-001',
    invoiceNumber: 'INV-2024-001',
    action: 'Sent to Review Queue: Amount exceeds ₹25,000 threshold',
    user: 'Workflow Engine',
    timestamp: '9 minutes ago',
    type: 'review',
  },
  {
    id: 'act-004',
    documentId: 'doc-002',
    invoiceNumber: 'INV-2024-002',
    action: 'Auto-approved & queued for payout',
    user: 'Workflow Engine',
    timestamp: '2 hours ago',
    type: 'approve',
  },
  {
    id: 'act-005',
    documentId: 'doc-007',
    invoiceNumber: 'INV-2024-007',
    action: 'Invoice rejected by System Admin due to missing GST details',
    user: 'System Admin',
    timestamp: '1 day ago',
    type: 'reject',
  },
];

export const MOCK_SETTINGS: WorkflowSettings = {
  automaticApprovalThreshold: 25000,
  aiConfidenceThreshold: 80,
  duplicateDetectionEnabled: true,
};

export const MOCK_ANALYTICS: AnalyticsData = {
  totalProcessed: 248,
  automationRate: 82,
  autoApproved: 185,
  manualReviews: 46,
  rejected: 17,
  monthlyTrend: [
    { month: 'May', total: 180, autoApproved: 140, manualReview: 40 },
    { month: 'Jun', total: 210, autoApproved: 168, manualReview: 42 },
    { month: 'Jul', total: 195, autoApproved: 155, manualReview: 40 },
    { month: 'Aug', total: 230, autoApproved: 188, manualReview: 42 },
    { month: 'Sep', total: 220, autoApproved: 178, manualReview: 42 },
    { month: 'Oct', total: 248, autoApproved: 185, manualReview: 63 },
  ],
};
